id: P007922
initial_creation_type: ocr
source_metadata:
  id: bdr:W1CZ2512
  title: འཁོར་ལོ་སྡོམ་པ་དྲིལ་བུ་ཕྱི་ནང་གི་བསྙེན་པ་བྱ་ཚུལ་གྱི་ཡི་གེ་མཁའ་འགྲོའི་གསང་མཛོད།
  author: ''
  volumes:
    abb2829196cb4067b886d95dfd76d1d7:
      image_group_id: I1KG1689
      title: ''
      volume_number: 1
      total_pages: 567
ebook_metadata:
  title: འཁོར་ལོ་སྡོམ་པ་དྲིལ་བུ་ཕྱི་ནང་གི་བསྙེན་པ་བྱ་ཚུལ་གྱི་ཡི་གེ་མཁའ་འགྲོའི་གསང་མཛོད།
  author: ''
  sku: P007922
  cover: cover.jpg
  layers:
  - pagination
