id: P007922
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1CZ2512
  title: འཁོར་ལོ་སྡོམ་པ་དྲིལ་བུ་ཕྱི་ནང་གི་བསྙེན་པ་བྱ་ཚུལ་གྱི་ཡི་གེ་མཁའ་འགྲོའི་གསང་མཛོད།
  author: ''
  volumes:
    faab0dc54d694e6fa71bb6d47b677863:
      image_group_id: I1KG1689
      title: Volume 1 of 'khor lo sdom pa dril bu phyi nang gi bsnyen pa bya tshul
        gyi yi ge mkha' 'gro'i gsang mdzod
      volume_number: 1
      total_pages: 567
      base_file: v001.txt
