id: I743609F3
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T17:11:41+00:00'
last_modified: '2022-06-09T07:32:17.308126+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1CZ2512
  title: འཁོར་ལོ་སྡོམ་པ་དྲིལ་བུ་ཕྱི་ནང་གི་བསྙེན་པ་བྱ་ཚུལ་གྱི་ཡི་གེ་མཁའ་འགྲོའི་གསང་མཛོད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    55A4:
      image_group_id: I1KG1689
      title: Volume 1 of 'khor lo sdom pa dril bu phyi nang gi bsnyen pa bya tshul
        gyi yi ge mkha' 'gro'i gsang mdzod
      total_pages: 567
      order: 1
      base_file: 55A4.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
